---

- hosts: servers

  gather_facts: true

  tasks:
   - name: Pushing SSH ID to Server(s)
     authorized_key:
      user: "{{  lookup('env','LOGNAME') }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

