---

- hosts: servers

  gather_facts: true
  become: yes

  tasks:
   - name: Update Cache and Patch all my servers
     apt:
      update_cache: yes
      upgrade: yes
      autoclean: yes
      autoremove: yes
