---

- hosts: servers

  gather_facts: yes
  become: yes

  tasks:
   - name: Update Cache and Patch all my servers
     apt:
      update_cache: yes
      upgrade: yes
      autoclean: yes
      autoremove: yes

   - name: Restart servers if needed
     shell: "[ -f /var/run/reboot-required ]"
     failed_when: False
     register: reboot_required
     changed_when: reboot_required.rc == 0
     notify: reboot

  handlers:
   - name: reboot
     command: /sbin/reboot
        
